name: Build documentation site

on:
  push:
    branches:
      - master
      - DD-1327

jobs:
  mkdocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt-openj9
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-docs-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-docs-

      - name: Generate maven site
        run: mvn -B clean test site jacoco:report coveralls:report --file pom.xml -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }} -Djarsigner.skip=true

      - name: Copy javadocs to site folder
        run: cp -r target/site/ docs/mvnsite/

      - name: Run script
        run: bash .github/workflows/mkdocs/mkdocs.sh
        shell: bash
